blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCategory,
    PostCreateView,
    PostUpdateView,
    UpdateComment,
    PostDeleteView,
    CommentDeleteView,
    UserPostListView,
    FollowsListView,
    test,
    ProfileListView,
    FollowersListView,
    ve,
    post_single,
    post_create,
    postpreference,
    commentpreference,)

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post_new/', post_create, name='create'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/<slug:slug>/', post_single, name='post_single'),
    path('test/', test, name='test'),
    path('post/category/<str:category>', PostCategory.as_view(), name='post-category'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('comment/<int:pk>/edit/', UpdateComment.as_view(), name='comment-update'),
    path('post/<int:pk>/del/<str:post/', PostDeleteView.as_view(), name='post-delete'),
    path('comment/<int:pk>/del/<str:post/', CommentDeleteView.as_view(), name='comment-delete'),
    path('user/<str:username>/follows', FollowsListView.as_view(), name='user-follows'),
    path('user/<str:username>/followers', FollowersListView.as_view(), name='user-followers'),
    path('user/<str:username>', ProfileListView.as_view(), name='user'),
    path('post/<int:postid>/<int:userpreference>', postpreference, name='postpreference'),
    path('comment/<int:postid>/<int:userpreference>', commentpreference, name='commentpreference'),
    path('v/', ve, name='vend'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from tinymce import HTMLField
from users import views as users_views
from dm.views import (
    ChannelDetailView,
    PrivateMessageDetailView
)

UUID_CHANNEL_REGEX = r'channel/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView
         .as_view(template_name='users/logins.html'), name='login'),  # class based views (
    # without templates
    # tho)
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password-reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password-reset-done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('register/', users_views.register, name='register-users'),
    path('profile/', users_views.profile, name='profile'),
    path('search/', users_views.SearchView, name='search'),
    path('', include('blog.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('tinymce/', include('tinymce.urls')),
    re_path(UUID_CHANNEL_REGEX, ChannelDetailView.as_view()),
    # re_path(r'channel/(?P<slug>[\w-]+)', ChannelSlugLookupView.as_view()),
    path("dm/<str:username>", PrivateMessageDetailView.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from tinymce import HTMLField
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.template.defaultfilters import slugify

class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    likes= models.IntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    dislikes= models.IntegerField(default=0)
    title = models.CharField(null=True, max_length=100)
    timestamp = models.DateTimeField(null=True,auto_now_add=True)
    slug = models.SlugField()
    date_posted = models.DateTimeField(default=timezone.now)
    content = HTMLField()
    thumbnail = models.ImageField(null=True, blank=True, upload_to='images/product')
    categories = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    featured = models.BooleanField(default=False)
    top = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        original_slug = slugify(self.title)
        queryset = Post.objects.all().filter(slug__iexact=original_slug).count()

        count = 1
        slug = original_slug
        while (queryset):
            slug = original_slug + '-' + str(count)
            count += 1
            queryset = Post.objects.all().filter(slug__iexact=slug).count()

        self.slug = slug

        if self.featured:
            try:
                temp = Post.objects.get(featured=True)
                if self != temp:
                    temp.featured = False
                    temp.save()
            except Post.DoesNotExist:
                pass
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    @property
    def number_of_comments(self):
        return Comment.objects.filter(post_connected=self).count()

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url \

    @property
    def ct(self):
        for i in range(1,100):
            x=i
        return x+1


    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk
        })

    def get_update_url(self):
        return reverse('post-update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('post-delete', kwargs={
            'pk': self.pk
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comments.objects.filter(post=self).count()



class Comment(models.Model):
    content = models.TextField(max_length=150)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_connected = models.ForeignKey(Post, on_delete=models.CASCADE)

class Comments(MPTTModel):
    author = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    likes = models.IntegerField(default=0)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='images/comment')
    dislikes = models.IntegerField(default=0)
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)


    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['publish']


    def get_update_url(self):
        return reverse('comment-update', kwargs={
            'pk': self.pk
        })


    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'pk': self.pk
        })

    @property
    def imageURL(self):
        try:
            url = self.thumbnail.url
        except:
            url = ''
        return url



class Preference(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    value= models.IntegerField()
    date= models.DateTimeField(auto_now= True)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)

    class Meta:
       unique_together = ("user", "post", "value")

class CommentPreference(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    post= models.ForeignKey(Comments, on_delete=models.CASCADE)
    value= models.IntegerField()
    date= models.DateTimeField(auto_now= True)

    def __str__(self):
        return str(self.user) + ':' + str(self.post) +':' + str(self.value)

    class Meta:
       unique_together = ("user", "post", "value")

blog/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comments,Category,Tag
from mptt.forms import TreeNodeChoiceField

class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False

class NewCommentForms(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 6, 'rows': 1}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'content', 'thumbnail',
                  'categories', 'featured')




class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 1}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'content', 'thumbnail',
        'categories', 'tag')

class PostFor(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 1}
        )
    )

    title = forms.CharField(widget=forms.Textarea(attrs={'overflow': 'auto', 'class': 'status-textarea', 'cols': 30, 'rows': 1, 'placeholder': 'Write something (title)'}))
    categories = forms.ModelChoiceField(queryset= Category.objects.all().order_by('title'), initial= 0, widget=forms.Select(attrs={'class': 'form-control','style':'width:50%;'}))
    tag = forms.ModelMultipleChoiceField(queryset= Tag.objects.all(), initial= 0, widget=forms.Select(attrs={'class': 'form-control', 'style':'width:50%;'}))

    class Meta:
        model = Post
        fields = ('title', 'content', 'thumbnail', 'categories', 'tag')





class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comments.objects.all())
    thumbnail = forms.FileField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comments
        fields = ('parent', 'content','thumbnail')

        widgets = {
            'content': forms.Textarea(attrs={'class': 'col-12','placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'}),
        }

    def save(self, *args, **kwargs):
        Comments.objects.rebuild()
        return super(NewCommentForm, self).save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['gender','date_of_birth','image','city','country','quote']

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Twitter</h1>
{% endblock content %}

blog/templates/blog/comment.html
{% extends "blog/main.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Contact Form Area -->

                    <div class="contact-form">
                        <div class="container">
                            <h3 class="white-important">
                                {{  tag_line }}
                            </h3>

                        {{ form.media }}
                            <form method="POST" class="col-12   no-padding pr-3 pr-md-0" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ form | crispy }}
                                </fieldset>
                                <div class="form-group">
                                    <button class="btn btn-outline-primary" type="submit">Submit changes</button>
                                </div>
                            </form>
                        </div>
                    </div>

            </div>
        </div>
    </section>

 {% endblock content %}

blog/templates/blog/comment_delete.html
{% extends "blog/main.html" %}
{% block content %}
<br>
<br>
<div class="container">
    <form method="POST" class="col-6 no-padding">
        {% csrf_token %}
        <fieldset class="form-group white-important">
            Do you really want to delete
        </fieldset>
        <p class="bg-steel p-2" style=" background-color:#a300cc; color:white; border: 1px solid white; border-radius: 4px; word-wrap: break-word;">
           {{ post.content }}
        </p>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Yes</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/follow.html
{% extends "blog/main.html" %}
{% block content %}

<br>
<br>
    <div class="container">
        <div class="row">
        {% if follow == 'follows' %}
             <div class="col-12 no-padding">
                <h3 class="white-important mb-3">
                    Following
                </h3>
                <div class="row pr-3 pl-3">
                    {% for follow in follows %}
                        <div class="col-6 col-md-3 pl-0">
                            <article class="media content-section">
                                <div>
                                    <img
                                               class="rounded-circle mr-2"
                                               style="width: 20px; height: 20px;"
                                               src="{{ follow.follow_user.profile.image.url }}">
                                   <a class="mr-2 white-important" href="{% url 'user-posts' follow.follow_user.username %}">
                                       {{ follow.follow_user.username }}
                                   </a>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        </div>
    </div>

        {% if follow == 'followers' %}
<div class="container">
        <div class="row">
             <div class="col-12 no-padding">
                <h3 class="white-important mb-3">
                    Followers
                </h3>
                <div class="row pr-3 pl-3">
                    {% for follow in follows %}
                        <div class="col-6 col-md-3 pl-0">
                            <article class="media content-section">
                                <div>
                                    <img
                                               class="rounded-circle mr-2"
                                               style="width: 20px; height: 20px;"
                                               src="{{ follow.user.profile.image.url }}">
                                   <a class="mr-2 white-important" href="{% url 'user-posts' follow.user.username %}">
                                       {{ follow.user.username }}
                                   </a>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>
            </div>
          </div>
    </div>
    {% endif %}
{% endblock content %}

blog/templates/blog/msg.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Dashboard v.1.0 | Adminpro - Admin Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <link rel="stylesheet" href="{% static 'blog/bootstrap.min1.css' %}">

    <link rel="stylesheet" href="{% static 'blog/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/jquery.mCustomScrollbar.min.css' %}">

    <link rel="stylesheet" href="{% static 'blog/animate.css' %}">

    <link rel="stylesheet" href="{% static 'blog/style_msg.css' %}">


</head>

<body class="materialdesign">

    <div class="chat-list-wrap">
        <div class="chat-list-adminpro">
            <div class="chat-button">
                <span data-toggle="collapse" data-target="#chat" class="chat-icon-link"><i class="fa fa-comments"></i></span>
            </div>
            <div id="chat" class="collapse chat-box-wrap shadow-reset animated zoomInLeft">
                <div class="chat-main-list">
                    <div class="chat-heading">
                        <h2>Messanger</h2>
                    </div>
                    <div class="chat-content chat-scrollbar">
                        <div class="author-chat">
                            <h3>Monica <span class="chat-date">10:15 am</span></h3>
                            <p>Hi, what you are doing and where are you gay?</p>
                        </div>
                        <div class="client-chat">
                            <h3>Mamun <span class="chat-date">10:10 am</span></h3>
                            <p>Now working in graphic design with coding and you?</p>
                        </div>
                        <div class="author-chat">
                            <h3>Monica <span class="chat-date">10:05 am</span></h3>
                            <p>Practice in programming</p>
                        </div>
                        <div class="client-chat">
                            <h3>Mamun <span class="chat-date">10:02 am</span></h3>
                            <p>That's good man! carry on...</p>
                        </div>
                    </div>
                    <div class="chat-send">
                        <input type="text" placeholder="Type..." />
                        <span><button type="submit">Send</button></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Chat Box End-->

    <script src="{% static 'jquery-1.11.3.min.js' %}"></script>

    <script src="{% static 'bootstrap.min.js' %}"></script>

    <script src="{% static 'jquery.meanmenu.js' %}"></script>

    <script src="{% static 'jquery.mCustomScrollbar.concat.min.js' %}"></script>

    <script src="{% static 'jquery.sticky.js' %}"></script>
    <script src="{% static 'main.js' %}"></script>
</body>

</html>

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container">
    <form method="POST" class="col-6 no-padding">
        {% csrf_token %}
        <fieldset class="form-group white-important">
            Do you really want to delete
        </fieldset>
        <p class="bg-steel p-2"
           style="border: 1px solid white; border-radius: 4px; word-wrap: break-word;">
           {{ post.content }}
        </p>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Yes</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends "blog/main.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

    <!-- ***** Header Area End ***** -->

    <!-- ********** Hero Area Start ********** -->
     <div class="hero-area height-700 bg-img background-overlay" style="background-image: url({% static 'img/blog-img/pexels_4.jpg' %});">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center">
                <div class="col-12 col-md-8 col-lg-6">
                    <div class="single-blog-title text-center">
                        <!-- Catagory -->
                                <div class="post-ctaa" style="margin:0px;top:0px;"><a href="#">Create New Post</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Contact Form Area -->

                    <div class="contact-form">
                        <div class="container">
                            <h3 class="white-important">
                                {{  tag_line }}
                            </h3>

                        {{ form.media }}
                            <form method="POST" class="col-12   no-padding pr-3 pr-md-0" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ form | crispy }}
                                </fieldset>
                                <div class="form-group">
                                    <button class="btn btn-outline-primary" type="submit">Submit changes</button>
                                </div>
                            </form>
                        </div>
                    </div>

            </div>
        </div>
    </section>
{% endblock content %}

blog/templates/blog/single.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title>{% block title %} Welcome to blog {% endblock %}</title>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in category_list %}
            <a class="dropdown-item" href="/category/{{ category.name}}">
              {{ category.name|title }}
            </a>
            {% endfor %}
          </div>
        </li>
      </ul>
    </div>
  </nav>
<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-7">
      <h1>{{post.title}}</h1>
    </div>
    <div class="col-md-9"><img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}"></div>
    <div class="col-md-7">
      <p>{{post.content|safe}}</p>
    </div>
    <div class="col-md-7">

      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}

      {% load mptt_tags %}

      <div>
        {% recursetree comment %}
        <div id="{{ node.id }}" class="my-2 p-2" style="border: 1px solid grey">
          <div class="d-flex justify-content-between">By {{ node.name }}<div></div>{{ node.publish }}</div>
          <div>{{ node.id }}{{ node.parent }}</div>
          <div>{{ node.content }}</div>
          <hr />
          {% if node.level < 3 %}
          <button class="button" onclick="myFunction({{ node.id }})">Reply</button>
          {% endif %}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>

      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <div id="myDIV" style="display:block;">
        <form id="myForm" method="post">
          <h2>Create new comment</h2>
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
        </form>
      </div>

    </div>
  </div>
</div>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>
<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form id="newForm" class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                <label for="id_name">Name:</label> \
                <input type="text" name="name" class="col-sm-12" maxlength="50" required="" id="id_name">\
                <select name="parent" class="d-none" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
                <label for="id_email">Email:</label> \
                <input type="text" name="email" class="col-sm-12" maxlength="254" required="" id="id_email"> \
                <label for="id_content">Content:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button> \
              </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>